links:
  consume:
    - auto: false
      min: 1
      max: 9999
      role: node
      argname: nodes

    - auto: false
      min: 0
      max: 257
      role: ardb
      argname: ardbs

    - auto: false
      min: 0
      max: 257
      role: filesystem
      argname: filesystems
