links:
  parent:
    optional: false
    auto: false
    role: node
    argname: node
  consume:
    - auto: false
      min: 0
      max: 1
      role: zerotier
      argname: zerotier
    - auto: false
      min: 0
      max: 9999
      role: bridge
      argname: bridges
    - auto: false
      min: 0
      max: 9999
      role: filesystem
      argname: filesystems

recurring:
  - action: monitor
    log: true
    period: 30m
